service: serverless-crud

provider:
  name: aws
  runtime: python3.10
  iam:
    role:
      statements:
        - Effect: Allow
          Action: dynamodb:*
          Resource: !GetAtt usersTable.Arn

plugins:
  - serverless-dynamodb
  - serverless-offline

custom:
  # dynamodb local
  serverless-dynamodb:
    stages:
      - dev
    start:
      docker: true
      port: 8000
      inMemory: true
      migrate: true

package:
  individually: true
  patterns:
    - '!./**'
    - '*.py'

functions:
  get-users:
    handler: get_users/get_users.handler
    events:
      - http:
          path: users/{id}
          method: GET

  create-users:
    handler: create_users/create_users.handler
    events:
      - http:
          path: users
          method: POST

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: pk
            AttributeType: S
        KeySchema:
          - AttributeName: pk
            KeyType: HASH
        TableName: users-table
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
