name: Deploy DEV

on:
  pull_request:
    branches: [ main ]

jobs:
  # TODO: install python dependencies if any and run python unit tests
  testing-changes:
    runs-on: ubuntu-latest
    name: Build/Test
    steps:
    - uses: actions/checkout@v2

    - name: NPM - Install dependencies
      if: steps.cached-npm-dependencies.outputs.cache-hit != 'true'
      run: 'npm install'  

  build-layers:
    runs-on: ubuntu-latest
    name: Build Layers
    steps:
    - uses: actions/checkout@v2

    - run: |
        pip install -r thumbnail/requirements.txt -d .Python/image_processing/python/
        zip -r image-processing.zip 
    
    - uses:

  deploy-env:
    permissions: 
      pull-requests: write 
    name: Deploy Lambda
    runs-on: ubuntu-latest
    needs: testing-changes
    steps:
    - uses: actions/checkout@v2.0.0

    - name: NPM - Load cached venv
      id: cached-npm-dependencies
      uses: actions/cache@v2
      with:
        path: node_modules
        key: npm-${{ runner.os }}-${{ hashFiles('**/package.json') }}

    - name: NPM - Install dependencies
      if: steps.cached-npm-dependencies.outputs.cache-hit != 'true'
      run: 'npm install'

    - name: Deploy using sls
      run: 'npx sls deploy'
      env:
        AWS_ACCESS_KEY_ID: ${{secrets.AWS_ACCESS_KEY_ID}}
        AWS_SECRET_ACCESS_KEY: ${{secrets.AWS_SECRET_ACCESS_KEY}}

    - name: Comment PR
      uses: thollander/actions-comment-pull-request@v1
      with:
        message: |
          Your SLS App was deployed!
          Awesome :D

        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}